import = ["/Users/andrewweber/.config/alacritty/themes/dracula.toml"]
"window.opacity" = 0.94

[colors]
draw_bold_text_with_bright_colors = false

[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.bold]
family = "CaskaydiaCove Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"
style = "Regular"

[window]
dynamic_padding = true

[window.dimensions]
columns = 110
lines = 40

[window.padding]
x = 10
y = 10
