[window]
opacity = 0.9
padding = {x = 10, y = 10}

[font]
size = 15.0

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

